/*
 * This source file was generated by the Gradle 'init' task
 */
package ex04_oop;

import java.util.ArrayList;
import java.util.List;

public class App {
    public static void main(String[] args) {
        // 학생 1번 정보 (절차적 방식)
        String stdName1 = "Kim";
        int stdAge1 = 20;
        int stdScore1 = 95;
    
        // 학생 2번 정보
        String stdName2 = "Lee";
        int stdAge2 = 21;
        int stdScore2 = 100;
    
        System.out.println(stdName1);
    
        // 객체지향 방식
        class Student {
            public Student() {

            }

            public Student(String name, int age, int score) {
                //TODO Auto-generated constructor stub
                this.name = name;
                this.age = age;
                this.score = score;
            }

            String name;
            int age;
            int score;

            void introduce() {
                System.out.println("이름: " + name + " 나이: " + age);
            }
        }
    
        // 객체지향은 그룹핑(단위 묶음)
        Student std1 = new Student(); // 객체 생성 후 기본생성자
        std1.name = "Kim"; // 각 멤버변수에 값 할당
        std1.age = 20;
        std1.score = 95;

        // Student std2 = new Student();
        // std2.name = "Lee";
        // std2.age = 21;
        // std2.score = 100;

        // System.out.println(std1.name + ", " + std1.age);

        // 클래스 메서드 사용방법
        // 파라미터 생성자
        Student std2 = new Student("Kim", 20, 95);
        std2.introduce();

        // 객체 활용방법
        List<Student> students = new ArrayList<>();

        // 데이터 추가
        students.add(new Student("유고", 49, 95));
        students.add(new Student("요미", 28, 90));
        students.add(new Student("철수", 35, 100));

        Account myAcc = new Account();
        // myAcc.balance = -100000;  // 누구나(개발자) 잔고라는 멤버변수에 접근가능
        myAcc.deposit(2000000);

        System.out.println("계좌 잔고는 : " + myAcc.getBalance());
        myAcc.withdraw(300000000);
        System.out.println("계좌 잔고는 : " + myAcc.getBalance());

        // 동물 클래스, 개 클래스 사용
        Animal ani = new Animal();
        ani.sound();
        ani.printName();

        Dog dog = new Dog();
        dog.sound();
        dog.printName();

        // 업캐스팅
        Animal a1 = new Dog();
        a1.sound();

        // 다운캐스팅
        // 자식클래스로 다시 변환전에 정확한 타입을 확인
        if (a1 instanceof Dog) {
            Dog c1 = (Dog)a1;
            c1.printName();
        }
        
        System.out.println("복사 학습 =====> ");

        // 복사
        Student s1 = new Student();
        s1.name = "유고";

        Student s2 = s1; // 복사
        s2.name = "이지";

        System.out.println(s1.name);
        System.out.println(s2.name);

        // 깊은 복사
        Student s3 = new Student();
        s3.name = "복이";

        Student s4 = new Student();
        s4.name = s3.name;
        s4.name = "애슐리";

        System.out.println(s3.name);
        System.out.println(s4.name);
    }
}

// 계좌 정보 클래
class Account { // 계좌 클래스
    private int balance; // 잔고

    // 입금, 여기서만 돈을 입금할 수 있고
    public void deposit(int amount) {
        if (amount > 0) {
            this.balance += amount;
        }
    }

    // 출금, 여기서만 돈을 출금할 수 있고
    public void withdraw(int amount) {
        if (amount > 0 && this.balance >= amount) {
            this.balance -= amount;
        }
    }

    // 잔고확인은 여기서만
    public int getBalance() {
        return this.balance;
    }
}

class Animal {
    String name = "동물";

    void sound() {
        System.out.println("동물 소리");
    }

    void printName() {
        System.out.println(this.name);
    }
}

// Animal 상속에서 Dog 클래스 선언
class Dog extends Animal {
    String name = "강아지";

    @Override
    void sound() {
        System.out.println("멍멍!");
    }

    @Override
    void printName() {
        System.out.println(super.name);
        System.out.println(this.name);
    }
}

class Cat extends Animal implements iCage {
    String name = "고양이";

    @Override
    void sound() {
        System.out.println("야옹!");
    }

    @Override
    void printName() {
        System.out.println(super.name + " / " + this.name);
    }

    @Override
    public void checkIn() {
        System.out.println("집에 가둠!");
    }

    @Override
    public void checkOut() {
        System.out.println("집에서 쫓아냄. 청소할꺼임!");
    }
}